// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiaehqtrbvcewosteapt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpYWVocXRyYnZjZXdvc3RlYXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTUzMjksImV4cCI6MjA3MTM3MTMyOX0.pRRRnIphVYWPv6vUdTsOOJ62EBVJ5kzN3ptMbn_CH7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});